### ISSUE TITLE
TypeError: unsupported operand type(s) for +: "int" and "NoneType" while run `python train.py`

### ISSUE THREAD

**Issue by happylicio** [hjweide/adversarial-autoencoder#1]
My way to solve this TypeError is rewriting the function of get_output_shape_for in Class ConCatLayer, compatibility with summarizing while `None` in `sizes` . But rewriting package's function seems a little tricky. @hjweide , how did you do?

**Comment by hjweide** [comment]
@happylicio, I'm afraid I don't entirely understand what you're asking.  Running `python train.py` works for me using the latest versions of Lasagne and Theano.  Could you please provide steps to reproduce this issue, perhaps with some terminal output?

**Comment by happylicio** [comment]
I'm sorry for not noting your reply timely. The following picture addresses the TypeError when I firstly run your code `python train.py`.
![image](https://cloud.githubusercontent.com/assets/18717873/20521024/3bfd454a-b0e4-11e6-9c11-cf71fa92c0b2.png)
According to the Traceback, the error case is like sum([None, None, ...]). So I rewrite the code in `lasagne/layers/merge.py` and successfully run your code. But this way is a little tricky cause rewriting lasagne library code. I just wanna whether you have the same problem and your way to solving it.  
BTW, your blog and implementation adversarial-autoencoder are an awesome work and help me a lot.

**Comment by hjweide** [comment]
Are you perhaps using an old version of Lasagne?  You'll notice that the [`ConcatLayer`](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/merge.py#L289) already deals with `None` in the input shape:
```
# Infer output shape on concatenation axis and return
sizes = [input_shape[self.axis] for input_shape in input_shapes]
concat_size = None if any(s is None for s in sizes) else sum(sizes)
output_shape[self.axis] = concat_size
return tuple(output_shape)
```
Also, thank you, I'm glad to hear that my code was useful to you :)
